# Generated by Django 3.0.3 on 2020-02-08 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=50)),
                ('admin_password', models.CharField(max_length=100)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='class_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_num', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='student_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xxtj.class_information')),
            ],
        ),
        migrations.CreateModel(
            name='statistics_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistics_name', models.CharField(default='none', max_length=20)),
                ('statistics_description', models.CharField(max_length=4096)),
                ('isDelete', models.BooleanField(default=False)),
                ('statistics_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xxtj.class_information')),
            ],
        ),
        migrations.CreateModel(
            name='recond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField()),
                ('inf', models.CharField(max_length=10240)),
                ('url', models.CharField(max_length=10240)),
                ('isDelete', models.BooleanField(default=False)),
                ('statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xxtj.statistics_information')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xxtj.student_information')),
            ],
        ),
        migrations.CreateModel(
            name='admin_statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xxtj.admin_information')),
                ('statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xxtj.statistics_information')),
            ],
        ),
    ]
